<Project Sdk="MSTest.Sdk/3.9.1">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.*" />
    <PackageReference Include="FluentAssertions" Version="8.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.*" />
    <!--
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    -->
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest" Version="3.9.*" />
    <PackageReference Include="MSTest.Analyzers" Version="3.9.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!--<PackageReference Include="MSTest.TestAdapter" Version="3.9.*" />-->
    <!--<PackageReference Include="MSTest.TestFramework" Version="3.9.*" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CS2Hub\Soft.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="17.14.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestAdapter" Version="3.9.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestFramework" Version="3.9.1" />
  </ItemGroup>

</Project>
